table fact_event_odds
	lineageTag: a0dd371e-5c05-4b32-ba68-82469e904ff2

	column as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9f602ed-00d0-4a0f-8c18-d551e9c0cae1
		summarizeBy: none
		sourceColumn: as_of

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column market_id
		dataType: string
		lineageTag: 8829457e-2d13-4290-bc47-37cbb5dd2d56
		summarizeBy: none
		sourceColumn: market_id

		annotation SummarizationSetBy = Automatic

	column event_title
		dataType: string
		lineageTag: 7efced39-5882-4553-a3e7-20f0c5810e3c
		summarizeBy: none
		sourceColumn: event_title

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 0257c3ae-8164-47d3-8b07-8e07cfa3ea88
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 7a45cfaa-f849-41f0-bb2e-d9c20bb011f5
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column yes_price
		dataType: double
		lineageTag: 8ed1f6d9-122f-47f7-af8b-4151ce20392f
		summarizeBy: sum
		sourceColumn: yes_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prob_change_1d
		dataType: double
		lineageTag: 46dcca8c-d768-4154-9b95-e0f8866bd5cc
		summarizeBy: sum
		sourceColumn: prob_change_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volume_24h
		dataType: double
		lineageTag: 4d4c085b-bbcc-4595-a3dc-9da0763fb2e3
		summarizeBy: sum
		sourceColumn: volume_24h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d02c2025-24f4-4cc5-9ce5-8074d0449386
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_event_odds = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ExportFolder & "\fact_event_odds.csv"), [Delimiter = ",", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Headers, {{"as_of", type date}, {"market_id", type text}, {"event_title", type text}, {"question", type text}, {"category", type text}, {"yes_price", type number}, {"prob_change_1d", type number}, {"volume_24h", type number}, {"end_date", type date}})
				in
					Typed

