-- LP Lens Snowflake objects. Run by hand in Snowsight as ACCOUNTADMIN (Run All).
--
-- Idempotent: every statement is CREATE IF NOT EXISTS / GRANT, so a second run is safe.
-- Values in angle brackets are filled locally and never committed:
--   <transformer-rsa-public-key>   public half of the TRANSFORMER service user's key
--   <loader-rsa-public-key>        public half of the LOADER service user's key
--   <reporter-rsa-public-key>      public half of the REPORTER service user's key
-- The matching private keys stay on the operator's machine and in CI secrets, never in this repo.
--
-- Object names here must stay equal to the defaults in infra/snowflake/sfconn.py and
-- warehouse/profiles.yml. Change one, change all three.
--
-- Designed, not deployed: this file has not been applied to a real account from this repository.

USE ROLE ACCOUNTADMIN;

-- -----------------------------------------------------------------------------
-- Compute and the cost cap
-- -----------------------------------------------------------------------------
-- One X-Small warehouse for load, transform and report. AUTO_SUSPEND = 60 so an idle
-- session does not keep billing. The resource monitor caps warehouse credits only;
-- Cortex and compute pools sit outside it, which is why PUBLIC loses those privileges
-- at the bottom of this file.
CREATE WAREHOUSE IF NOT EXISTS LP_LENS_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'LP Lens: single warehouse for load, dbt and reporting';

CREATE RESOURCE MONITOR IF NOT EXISTS LP_LENS_RM
    WITH CREDIT_QUOTA = 20
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE LP_LENS_WH SET RESOURCE_MONITOR = LP_LENS_RM;

-- Trial / leftover warehouses, if they exist, go under the same cap so they cannot
-- run away independently of the project warehouse.
ALTER WAREHOUSE IF EXISTS COMPUTE_WH SET AUTO_SUSPEND = 60 RESOURCE_MONITOR = LP_LENS_RM;
ALTER WAREHOUSE IF EXISTS SNOWFLAKE_LEARNING_WH SET AUTO_SUSPEND = 60 RESOURCE_MONITOR = LP_LENS_RM;

-- -----------------------------------------------------------------------------
-- Databases and permanent schemas
-- -----------------------------------------------------------------------------
-- INTERMEDIATE is required by the dbt project (Python return models materialize as
-- tables there). RAW / STAGING / MARTS are the layers the playbook names.
CREATE DATABASE IF NOT EXISTS LP_LENS_DEV;
CREATE DATABASE IF NOT EXISTS LP_LENS_PROD;

CREATE SCHEMA IF NOT EXISTS LP_LENS_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS LP_LENS_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS LP_LENS_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS LP_LENS_DEV.MARTS;

CREATE SCHEMA IF NOT EXISTS LP_LENS_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS LP_LENS_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS LP_LENS_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS LP_LENS_PROD.MARTS;

-- Internal stages. RAW.LP_LENS_RAW holds the Parquet snapshot; RAW.LP_LENS_PACKAGES
-- holds the slim lp_lens metrics wheel that Snowpark Python models import.
CREATE STAGE IF NOT EXISTS LP_LENS_DEV.RAW.LP_LENS_RAW
    FILE_FORMAT = (TYPE = PARQUET USE_LOGICAL_TYPE = TRUE)
    COMMENT = 'LP Lens: PUT destination for data/raw Parquet';
CREATE STAGE IF NOT EXISTS LP_LENS_DEV.RAW.LP_LENS_PACKAGES
    COMMENT = 'LP Lens: slim lp_lens metrics wheel for Snowpark';
CREATE STAGE IF NOT EXISTS LP_LENS_PROD.RAW.LP_LENS_RAW
    FILE_FORMAT = (TYPE = PARQUET USE_LOGICAL_TYPE = TRUE);
CREATE STAGE IF NOT EXISTS LP_LENS_PROD.RAW.LP_LENS_PACKAGES;

CREATE FILE FORMAT IF NOT EXISTS LP_LENS_DEV.RAW.LP_LENS_PARQUET
    TYPE = PARQUET
    USE_LOGICAL_TYPE = TRUE;
CREATE FILE FORMAT IF NOT EXISTS LP_LENS_PROD.RAW.LP_LENS_PARQUET
    TYPE = PARQUET
    USE_LOGICAL_TYPE = TRUE;

-- -----------------------------------------------------------------------------
-- Roles
-- -----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS LP_LENS_LOADER;
CREATE ROLE IF NOT EXISTS LP_LENS_TRANSFORMER;
CREATE ROLE IF NOT EXISTS LP_LENS_REPORTER;

GRANT USAGE ON WAREHOUSE LP_LENS_WH TO ROLE LP_LENS_LOADER;
GRANT USAGE ON WAREHOUSE LP_LENS_WH TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE ON WAREHOUSE LP_LENS_WH TO ROLE LP_LENS_REPORTER;

GRANT MONITOR ON RESOURCE MONITOR LP_LENS_RM TO ROLE LP_LENS_TRANSFORMER;

-- LOADER: write RAW (and CI raw schemas), nothing in MARTS.
GRANT USAGE ON DATABASE LP_LENS_DEV TO ROLE LP_LENS_LOADER;
GRANT USAGE ON DATABASE LP_LENS_PROD TO ROLE LP_LENS_LOADER;
GRANT CREATE SCHEMA ON DATABASE LP_LENS_DEV TO ROLE LP_LENS_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA LP_LENS_DEV.RAW
    TO ROLE LP_LENS_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA LP_LENS_PROD.RAW
    TO ROLE LP_LENS_LOADER;
GRANT READ, WRITE ON STAGE LP_LENS_DEV.RAW.LP_LENS_RAW TO ROLE LP_LENS_LOADER;
GRANT READ, WRITE ON STAGE LP_LENS_DEV.RAW.LP_LENS_PACKAGES TO ROLE LP_LENS_LOADER;
GRANT READ, WRITE ON STAGE LP_LENS_PROD.RAW.LP_LENS_RAW TO ROLE LP_LENS_LOADER;
GRANT READ, WRITE ON STAGE LP_LENS_PROD.RAW.LP_LENS_PACKAGES TO ROLE LP_LENS_LOADER;

-- TRANSFORMER: read RAW, write STAGING / INTERMEDIATE / MARTS, create CI_* schemas.
GRANT USAGE ON DATABASE LP_LENS_DEV TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE ON DATABASE LP_LENS_PROD TO ROLE LP_LENS_TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE LP_LENS_DEV TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE ON SCHEMA LP_LENS_DEV.RAW TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE ON SCHEMA LP_LENS_PROD.RAW TO ROLE LP_LENS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LP_LENS_DEV.RAW TO ROLE LP_LENS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LP_LENS_PROD.RAW TO ROLE LP_LENS_TRANSFORMER;
GRANT READ ON STAGE LP_LENS_DEV.RAW.LP_LENS_PACKAGES TO ROLE LP_LENS_TRANSFORMER;
GRANT READ ON STAGE LP_LENS_PROD.RAW.LP_LENS_PACKAGES TO ROLE LP_LENS_TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_DEV.STAGING TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_DEV.INTERMEDIATE TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_DEV.MARTS TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_PROD.STAGING TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_PROD.INTERMEDIATE TO ROLE LP_LENS_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION
    ON SCHEMA LP_LENS_PROD.MARTS TO ROLE LP_LENS_TRANSFORMER;

-- REPORTER: SELECT on MARTS only. No RAW, no STAGING, no INTERMEDIATE.
GRANT USAGE ON DATABASE LP_LENS_DEV TO ROLE LP_LENS_REPORTER;
GRANT USAGE ON DATABASE LP_LENS_PROD TO ROLE LP_LENS_REPORTER;
GRANT USAGE ON SCHEMA LP_LENS_DEV.MARTS TO ROLE LP_LENS_REPORTER;
GRANT USAGE ON SCHEMA LP_LENS_PROD.MARTS TO ROLE LP_LENS_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LP_LENS_DEV.MARTS TO ROLE LP_LENS_REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LP_LENS_DEV.MARTS TO ROLE LP_LENS_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LP_LENS_PROD.MARTS TO ROLE LP_LENS_REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LP_LENS_PROD.MARTS TO ROLE LP_LENS_REPORTER;

-- -----------------------------------------------------------------------------
-- Service users (key-pair only; no passwords)
-- -----------------------------------------------------------------------------
CREATE USER IF NOT EXISTS LP_LENS_LOADER_USER
    TYPE = SERVICE
    DEFAULT_ROLE = LP_LENS_LOADER
    DEFAULT_WAREHOUSE = LP_LENS_WH
    DEFAULT_NAMESPACE = LP_LENS_DEV.RAW
    RSA_PUBLIC_KEY = '<loader-rsa-public-key>';
CREATE USER IF NOT EXISTS LP_LENS_TRANSFORMER_USER
    TYPE = SERVICE
    DEFAULT_ROLE = LP_LENS_TRANSFORMER
    DEFAULT_WAREHOUSE = LP_LENS_WH
    DEFAULT_NAMESPACE = LP_LENS_DEV.MARTS
    RSA_PUBLIC_KEY = '<transformer-rsa-public-key>';
CREATE USER IF NOT EXISTS LP_LENS_REPORTER_USER
    TYPE = SERVICE
    DEFAULT_ROLE = LP_LENS_REPORTER
    DEFAULT_WAREHOUSE = LP_LENS_WH
    DEFAULT_NAMESPACE = LP_LENS_DEV.MARTS
    RSA_PUBLIC_KEY = '<reporter-rsa-public-key>';

GRANT ROLE LP_LENS_LOADER TO USER LP_LENS_LOADER_USER;
GRANT ROLE LP_LENS_TRANSFORMER TO USER LP_LENS_TRANSFORMER_USER;
GRANT ROLE LP_LENS_REPORTER TO USER LP_LENS_REPORTER_USER;

-- -----------------------------------------------------------------------------
-- CI schema pattern
-- -----------------------------------------------------------------------------
-- dbt target snowflake_ci sets schema = $LP_LENS_CI_SCHEMA (e.g. CI_PR_4).
-- generate_schema_name then produces CI_PR_4_STAGING / CI_PR_4_INTERMEDIATE /
-- CI_PR_4_MARTS, so a PR build cannot overwrite the shared MARTS schema.
-- load_raw.py --raw-schema CI_PR_4_RAW writes that PR's snapshot next to them.
-- TRANSFORMER already has CREATE SCHEMA on LP_LENS_DEV; LOADER has the same so
-- it can create the per-PR RAW schema. Drop leftover CI_* schemas by hand after
-- the PR closes -- this file does not delete data.

-- -----------------------------------------------------------------------------
-- Trial defaults that bill outside the resource monitor
-- -----------------------------------------------------------------------------
REVOKE ALL PRIVILEGES ON WAREHOUSE SNOWFLAKE_LEARNING_WH FROM ROLE PUBLIC;
REVOKE ROLE SNOWFLAKE_LEARNING_ROLE FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU FROM ROLE PUBLIC;
REVOKE DATABASE ROLE SNOWFLAKE.CORTEX_USER FROM ROLE PUBLIC;
